int _strlen(char *s);
int _strcmp(char *s1, char *s2);
char *_strcat(char *dest, char *src);
char *_strncat(char *dest, char *src, int n);
char *_strncpy(char *dest, char *src, int n);
void print_array(int *a, int n);
int _atoi(char *s);
char *_strcpy(char *dest, char *src);
void puts_half(char *str);
void puts2(char *str);
int _putchar( char c);
void _puts(char *str);
void rev_string(char *s);
void reset_to_98(int *n);
void swap_int(int *a, int *b);
